# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import qtawesome
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.Qt import *


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 587)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 871, 40))
        self.widget.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 5, 181, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"黑体\";")
        self.label.setObjectName("label")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setGeometry(QtCore.QRect(830, 0, 41, 40))
        self.pushButton_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(790, 0, 41, 40))
        self.pushButton_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 40, 181, 531))
        #self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.toolBox = QtWidgets.QToolBox(self.widget_2)
        self.toolBox.setGeometry(QtCore.QRect(10, 120, 161, 351))
        self.toolBox.setMinimumSize(QtCore.QSize(4, 4))
        self.toolBox.setStyleSheet("font: 20pt \"黑体\";")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 161, 146))
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 9, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 161, 146))
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 9, 160, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 9, 160, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 9, 160, 131))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.toolBox.addItem(self.page_5, "")
        self.toolButton = QtWidgets.QToolButton(self.widget_2)
        self.toolButton.setGeometry(QtCore.QRect(16, 30, 151, 71))
        self.toolButton.setObjectName("toolButton")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(179, 40, 691, 531))
        self.widget_3.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.widget_3.setObjectName("widget_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 651, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.stackedWidget.addWidget(self.page_21)
        self.page_31 = QtWidgets.QWidget()
        self.page_31.setObjectName("page_31")
        self.stackedWidget.addWidget(self.page_31)
        self.page_41 = QtWidgets.QWidget()
        self.page_41.setObjectName("page_41")
        self.stackedWidget.addWidget(self.page_41)
        self.page_51 = QtWidgets.QWidget()
        self.page_51.setObjectName("page_51")
        self.stackedWidget.addWidget(self.page_51)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.stackedWidget.addWidget(self.page_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(4)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_13.clicked.connect(MainWindow.close)
        self.pushButton_14.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.menu = QtWidgets.QMenu(self.toolButton)
        self.menu.setStyleSheet("font: 16pt \"黑体\";")
        self.act1 = QtWidgets.QAction("个人", self.menu)
        self.menu.addAction(self.act1)
        self.act1.setData("点击了行为1")
        self.act2 = QtWidgets.QAction("收藏", self.menu)
        self.menu.addAction(self.act2)
        self.act2.setData("点击了行为1")
        self.act3 = QtWidgets.QAction("设置", self.menu)
        self.menu.addAction(self.act3)
        self.act3.setData("点击了行为1")
        self.act4 = QtWidgets.QAction("退出登录", self.menu)
        self.menu.addAction(self.act4)
        self.act4.setData("点击了行为1")
        self.toolButton.setPopupMode(QToolButton.InstantPopup)
        self.toolButton.setMenu(self.menu)


        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)  # 去除边框

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "xxx系统"))
        self.pushButton_13.setText(_translate("MainWindow", ""))
        self.pushButton_13.setIcon(qtawesome.icon('fa.close',color='#808080'))
        self.pushButton_13.setIconSize(QtCore.QSize(25, 31))
        self.pushButton_14.setText(_translate("MainWindow", ""))
        self.pushButton_14.setIcon(qtawesome.icon('fa.minus',color='#808080'))
        self.pushButton_14.setIconSize(QtCore.QSize(25, 31))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", " 首  页"))
        self.toolBox.setItemIcon(self.toolBox.indexOf(self.page), qtawesome.icon('fa.home',color='#2c3a45'))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", " 学校选择"))
        self.toolBox.setItemIcon(self.toolBox.indexOf(self.page_2), qtawesome.icon('mdi.school', color='#2c3a45'))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "log 3"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "log 4"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "log 5"))
        self.toolButton.setText(_translate("MainWindow", "username"))
        self.toolButton.setIcon(QtGui.QIcon('r.png'))
        self.toolButton.setIconSize(QtCore.QSize(50, 50))  # 设置图标大小
        self.toolButton.setAutoRaise(True)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setArrowType(Qt.NoArrow)
        self.toolButton.setToolTip("用户设置")

        self.pushButton_13.setStyleSheet(
        '''
        QPushButton{ padding-right:0px;color:#808080;font-size:16px;border:none;}
        QPushButton:hover{background:red;}
        ''')
        self.pushButton_14.setStyleSheet(
        '''
        QPushButton{ padding-right:0px;color:#808080;font-size:16px;border:none;}
        QPushButton:hover{background:#aaaaaa;}
        ''')
        self.widget_2.setStyleSheet(
        '''
        QToolButton{
        border:none;
        font-weight:600;
        font-size:16px;
        font-family:'微软雅黑';
        }
        QPushButton{
        border:none;
        font-family:'微软雅黑';
        height:70px;
        }
        QPushButton:hover{background:#aaaaaa;}
        QAction:hover{background:#aaaaaa;}
        ''')

def do_act():
    global ui
    print(ui.act1.data())

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    MainWindow = QtWidgets.QMainWindow()
    ui.setupUi(MainWindow)
    ui.toolButton.triggered.connect(do_act)
    MainWindow.show()
    sys.exit(app.exec_())