"""empty message

Revision ID: 06ca8899eb0d
Revises: 603d4ca42c74
Create Date: 2022-06-18 12:48:29.897373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ca8899eb0d'
down_revision = '603d4ca42c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collect', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'collect', ['user_id'])
    op.drop_constraint(None, 'collect', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collect', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'collect', type_='unique')
    op.alter_column('collect', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
