"""empty message

Revision ID: 1f1a32991510
Revises: 2da9f7802765
Create Date: 2022-06-18 11:01:31.972123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1a32991510'
down_revision = '2da9f7802765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collect', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collect', type_='foreignkey')
    # ### end Alembic commands ###
