"""empty message

Revision ID: 926754bd6bc9
Revises: 27bc825fc71c
Create Date: 2022-06-18 09:54:48.738871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926754bd6bc9'
down_revision = '27bc825fc71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    # ### end Alembic commands ###
